server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: sentinel-monitor-api
  jackson:
    default-property-inclusion: non_null
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

sentinel:
  snapshot-expire-seconds: 120
  features:
    persistence: false
    redis: false
    rabbitmq: false

